[colors]
ansi = [
    '#271426',
    '#f779b4',
    '#37816f',
    '#ffbc4d',
    '#9697ea',
    '#af74bd',
    '#f19ec5',
    '#ffe3f9', 
]
background = '#3c2e47'
brights = [
    '#271426',
    '#f779b4',
    '#37816f',
    '#ffbc4d',
    '#9697ea',
    '#af74bd',
    '#f19ec5',
    '#ffe3f9', 
]
cursor_bg = '#af74bd'
cursor_border = '#fddbff'
cursor_fg = '#fddbff'
foreground = '#fddbff'
scrollbar_thumb = '#af74bd'
selection_bg = '#d6c5d8'
selection_fg = '#3c2e47'

[metadata]
aliases = []
name = 'Nehellenia'
authors = [ 'sailorfe', 'morgansleeper' ]