[colors]
ansi = [
    '#423263',
    '#ff0083',
    '#00a294',
    '#ec8300',
    '#0c1eb8',
    '#7800b8',
    '#ff69d3',
    '#d6c5d8',
]
background = '#fcdeec'
brights = [
    '#624a73',
    '#ff0083',
    '#00a294',
    '#ec8300',
    '#0c1eb8',
    '#7800b8',
    '#ff69d3',
    '#e3d1e5',
]
cursor_bg = '#ff83fc'
cursor_border = '#fddbff'
cursor_fg = '#fddbff'
foreground = '#816297'
scrollbar_thumb = '#ffbc4d'
selection_bg = '#f19ec5'
selection_fg = '#f2bfc9'

[metadata]
aliases = [ 'Serenity', ]
name = 'Serenity'
authors = [ 'sailorfe', 'morgansleeper' ]