[colors]
ansi = [
    '#251d2d',
    '#ff0083',
    '#00a294',
    '#ec8300',
    '#0c1eb8',
    '#7800b8',
    '#ff69d3',
    '#d6c5d8',
]
background = '#ffd7e5'
brights = [
    '#4d3a5a',
    '#ff0083',
    '#00a294',
    '#ec8300',
    '#0c1eb8',
    '#7800b8',
    '#ff69d3',
    '#e3d1e5',
]
cursor_bg = '#8ae0d8'
cursor_border = '#fddbff'
cursor_fg = '#fddbff'
foreground = '#674e78'
scrollbar_thumb = '#ffbc4d'
selection_bg = '#f19ec5'
selection_fg = '#f2bfc9'

[metadata]
aliases = []
name = 'Serenity'
authors = [ 'sailorfe', 'morgansleeper' ]
