[colors]
ansi = [
    '#25253c',
    '#d90e7a',
    '#378a6f',
    '#ff9500',
    '#00a6e2',
    '#bf56ca',
    '#ff84fc',
    '#b7aedd',
]
background = '#1b1b2c'
brights = [
    '#25253c',
    '#d90e7a',
    '#378a6f',
    '#ff9500',
    '#00a6e2',
    '#bf56ca',
    '#ff84fc',
    '#b7aedd',
]
cursor_bg = '#9697ea'
cursor_border = '#9697ea'
cursor_fg = '#fdffdc'
foreground = '#d2c9da'
selection_bg = '#b175ac'
selection_fg = '#fef6eb'
scrollbar_thumb = '#38385b'
split = '#38385b'

[colors.tab_bar]
background = '#11111c'

[colors.tab_bar.active_tab]
bg_color = '#1b1b2c'
fg_color = '#fddbff'
italic = true

[colors.tab_bar.inactive_tab]
bg_color = '#38385b'
fg_color = '#fddbff'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#3e2e4c'
fg_color = '#fddbff'
italic = true

[colors.tab_bar.new_tab]
bg_color = '#38385b'
fg_color = '#fddbff'

[colors.tab_bar.new_tab_hover]
bg_color = '#3e2e5c'
fg_color = '#fddbff'
italic = true

[metadata]
aliases = []
author = 'sailorfe'
name = 'Moon Queen Nehellenia'
origin_url = 'https://codeberg.org/sailorfe/moon-queen'
