[colors]
ansi = [
    '#1d182e',
    '#fb569b',
    '#3461d8',
    '#b00c03',
    '#288a7a',
    '#fc8f0c',
    '#614abf',
    '#aabcea',
]
background = '#0d0917'
brights = [
    '#3a306f',
    '#fd8cda',
    '#4d8fe5',
    '#f72f39',
    '#66a799',
    '#fce815',
    '#8466f5',
    '#fcfdff',
]
cursor_bg = '#5c3e98'
cursor_border = '#5c3e98'
cursor_fg = '#aabcea'
foreground = '#edf7f9'
selection_bg = '#20093d'
selection_fg = '#fcfdff'
scrollbar_thumb = '#0b1753'
split = '#0b1753'

[colors.tab_bar]
background = '#00010e'

[colors.tab_bar.active_tab]
bg_color = '#0d0917'
fg_color = '#f0e7ea'
italic = true

[colors.tab_bar.inactive_tab]
bg_color = '#1a0c47'
fg_color = '#f0e7ea'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#3a306f'
fg_color = '#f0e7ea'
italic = true

[colors.tab_bar.new_tab]
bg_color = '#1a0c47'
fg_color = '#f0e7ea'

[colors.tab_bar.new_tab_hover]
bg_color = '#3a306f'
fg_color = '#f0e7ea'
italic = true

[metadata]
aliases = []
author = 'kdlrose'
name = 'Mugen'
origin_url = 'https://github.com/kdlrose/moon-queen'
