[colors]
ansi = [
    '#25253c',
    '#d90e7a',
    '#378a6f',
    '#ffbc4d',
    '#819ec0',
    '#bf56ca',
    '#ff84fc',
    '#8c8399',
]
background = '#1b1b2c'
brights = [
    '#25253c',
    '#d90e7a',
    '#378a6f',
    '#ffbc4d',
    '#819ec0',
    '#bf56ca',
    '#ff84fc',
    '#8c8399',
]
cursor_bg = '#9697ea'
cursor_border = '#9697ea'
cursor_fg = '#fdffdc'
foreground = '#fddbff'
selection_bg = '#b175ac'
selection_fg = '#fef6eb'
scrollbar_thumb = '#38385b'
split = '#38385b'

[colors.tab_bar]
background = '#11111c'

[colors.tab_bar.active_tab]
bg_color = '#1b1b2c'
fg_color = '#fddbff'
italic = true

[colors.tab_bar.inactive_tab]
bg_color = '#38385b'
fg_color = '#fddbff'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#3e2e4c'
fg_color = '#fddbff'
italic = true

[colors.tab_bar.new_tab]
bg_color = '#38385b'
fg_color = '#fddbff'

[colors.tab_bar.new_tab_hover]
bg_color = '#3e2e5c'
fg_color = '#fddbff'
italic = true

[metadata]
aliases = []
author = 'sailorfe'
name = 'Moon Queen Nehellenia'
upstream = 'https://github.com/sailorfe/moon-queen/blob/main/colors/nehellenia.toml'
