[colors]
ansi = [
    '#4c2d59',
    '#fc2fb2',
    '#134db1',
    '#de2230', 
    '#318509',
    '#fd7102',
    '#7441ba',
    '#d6c1ec',
]
background = '#fcdff8'
brights = [
    '#725b91',
    '#ff70f3',
    '#3098d7',
    '#ff4f7e', 
    '#85bd12',
    '#fac529',
    '#8c4ee2',
    '#e6d0f4',
]
cursor_bg = '#e871a9'
cursor_border = '#e871a9'
cursor_fg = '#f9f8fe'
foreground = '#553f6d'
selection_bg = '#f2b8da'
selection_fg = '#b76dc2'
scrollbar_thumb = '#f1cdf3'
split = '#f1cdf3'

[colors.tab_bar]
background = '#fcc8ef'

[colors.tab_bar.active_tab]
bg_color = '#fcdff8'
fg_color = '#553f6d'
italic = true

[colors.tab_bar.inactive_tab]
bg_color = '#fcc8ef'
fg_color = '#553f6d'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#f99fdf'
fg_color = '#553f6d'
italic = true

[colors.tab_bar.new_tab]
bg_color = '#f1cdf3'
fg_color = '#553f6d'

[colors.tab_bar.new_tab_hover]
bg_color = '#f99fdf'
fg_color = '#553f6d'
italic = true

[metadata]
aliases = []
author = 'kdlrose'
name = 'Yume'
origin_url = 'https://github.com/kdlrose/moon-queen'
